[build]
  functions = "functions"
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200
  
[build]
  command = "echo 'Build complete!'"  # Bisa kosong, Netlify hanya perlu sesuatu di sini
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache"

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/urls.json"]

[build]
  command = "echo 'Build complete!'"  # Tidak ada build, hanya untuk memaksa deploy
  functions = "functions"

[functions]
  included_files = ["functions/urls.json"]  # Pastikan Netlify menyertakan JSON saat build
  
[build]
  command = "echo 'Build complete!'"  # Hanya untuk memastikan deploy berjalan
  functions = "functions"

[functions]
  included_files = ["functions/urls.json"]  # Pastikan Netlify menyertakan file JSON
  
[build]
  command = "echo 'Build complete!'"  # Memaksa deploy ulang
  functions = "functions"
