[build]
  functions = "functions"

[build]
  functions = "functions"
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200

[functions]
  node_bundler = "esbuild"
